config/routes.rb
Rails.application.routes.draw do
	
  resources :degrees
  resources :photos
  # dashboard links for member

  # CSV Exports for ecmembers, committee members, members
  get "/export-ecmembers" => 'ecmembers#csv_export', as: 'csv_export_ecmembers'
  get "/export-committee_members" => 'committee_members#csv_export', as: 'csv_export_committee_members'
  get "/export-members" => 'members#csv_export', as: 'csv_export_members'


  get "/d/announcements" => "dashboard#announcements"
  get "/d/announcement/:id" => "dashboard#announcement", as: 'd_announcement'
  get "/d/attachments" => "dashboard#attachments"
  get "/d/attachment/:id" => "dashboard#attachment", as: 'd_attachment'
  get "/d/members" => "dashboard#members"
  get "/d/member_information" => "dashboard#member"
  get "/d/organizations" => "dashboard#organizations"
  get "/d/ecmembers" => "dashboard#ecmembers"
  get "/d/committees" => "dashboard#committees"
  get "/d/committee_members" => "dashboard#committee_members"



  # Edit password only
  get '/users/edit_information' => "users#edit_information", as: 'user_edit_information'
  post '/users/update_information' => "users#update_information", as: 'user_update_information'


  post '/users' => 'users#create'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }, path_names: {sign_up: 'creating_an_account_is_not_an_option' }
  
  resources :api_keys
  resources :announcements

  resources :committee_members
  resources :ecmembers
  resources :members
  resources :users
  
  resources :membership_applications
  resources :memberships
  resources :attachments
  resources :requests
  
  resources :committees
  resources :organizations

  # resources :access_controls
  # resources :permissions
  # resources :events
  # resources :member_data
  # resources :comittees
  
  get '/apply' => 'membership_applications#new', as: 'new_application'
	
  resources :states
  resources :townships
  resources :staffs

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # township populated when state is chosen
  get '/state_search' => 'membership_applications#state_search', as: 'state_search'

  # Email and role populated according to staff or member id in user form
  get '/populate_by_staff_id' => 'users#populate_by_staff_id', as: 'populate_by_staff_id'
  get '/populate_by_member_id' => 'users#populate_by_member_id', as: 'populate_by_member_id'

  root to: 'dashboard#index' 
  get 'index.xlsx' => 'members#export_excel'



  # Extend/Upgrade membership
  get '/memberships/:id/upgrade' => 'memberships#upgrade', as: 'upgrade_membership'
  post '/memberships/:id/upgrade' => 'memberships#upgraded'
  get '/memberships/:id/extend' => 'memberships#extend', as: 'extend_membership'
  post '/memberships/:id/extend' => 'memberships#extended'

  get 'requests/:id/accept' => 'requests#accept', as: 'accept_request'
  get 'requests/:id/reject' => 'requests#reject', as: ''

  get '/reports' => "report#index", as: 'report'

  get '/successful' => "membership_applications#successful"
  get '/accept/:id' => "membership_applications#accept", as: 'accept_membership_application_request'
  get '/reject/:id' => "membership_applications#reject", as: 'reject_membership_application_request'
  get '/done' => "membership_applications#done"
 
# CSV import for existing member list for each organization
  get '/csv_import' => 'members#csv_import', as: "csv_import"
  post '/member_list_csv_import' => 'members#member_list_csv_import', as: "member_list_csv_import"


# API key and Api 
  get '/display' => 'api_version1#display'
  get '/access_control/:id' => 'api_version1#access_control'
  get '/announcement/:id' => 'api_version1#announcement'
  get '/attachment/:id' => 'api_version1#attachment'


  get '/ecmember/:id' => 'api_version1#ecmember'
  get '/event/:id' => 'api_version1#event'
  get '/member_datum/:id' => 'api_version1#member_datum'
  get '/member/:id' => 'api_version1#member'
  get '/membership_application/:id' => 'api_version1#membership_application'
  get '/membership/:id' => 'api_version1#membership'
  get '/organization/:id' => 'api_version1#organization'

  get '/staff/:id' => 'api_version1#staff'
  get '/state/:id' => 'api_version1#state'
  get '/township/:id' => 'api_version1#township'
  get '/user/:id' => 'api_version1#user'


  get '/member_info_edit' => "members#member_info_edit"
  post '/member_info_edit' => "members#member_info_update"


  get '/member_search' => "ecmembers#member_search"


  get "/organization_lvl_report" => "report#organization_lvl_report"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
	validates_presence_of :title, :date, :content

	belongs_to :organization, optional: true
	belongs_to :committee, optional: true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  # before_action :authenticate_user!
  before_action :is_staff?#, except: [:index, :show]
  before_action :is_admin?, only: [:destroy]
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    if current_user.role == "Admin"
      @announcements = Announcement.all.order(date: :DESC)
    else
      @announcements = Announcement.where(organization_id: [nil, current_user.staff.organization.id])
    end
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @text = "show"
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
    if current_user.role == 'Admin' || current_user.staff.organization.organization_name == "Myanmar Computer Professionals Association"
      @organizations = Organization.all.collect {|o| [o.organization_name, o.id]}
    else
      @organizations = Organization.where(id: current_user.staff.organization.id).collect {|o| [o.organization_name, o.id]}
    end

  end

  # GET /announcements/1/edit
  def edit
    if current_user.role == 'Admin' || current_user.staff.organization.organization_name == "Myanmar Computer Professionals Association"
      @organizations = Organization.all.collect {|o| [o.organization_name, o.id]}
    else
      @organizations = Organization.where(id: current_user.staff.organization.id).collect {|o| [o.organization_name, o.id]}
    end
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        # @notice = "Announcement was successfully created."
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        if current_user.role == 'Admin' || current_user.staff.organization.organization_name == "Myanmar Computer Professionals Association"
          @organizations = Organization.all.collect {|o| [o.organization_name, o.id]}
        else
          @organizations = Organization.where(id: current_user.staff.organization.id).collect {|o| [o.organization_name, o.id]}
        end
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcements = current_user.role == 'Staff' ?  Announcement.where(organization_id: [nil, current_user.staff.organization.id]) : Announcement.all
      if @announcements.ids.include? (params[:id].to_i)
        @announcement = Announcement.find(params[:id])
      else
        redirect_to announcements_path, notice: 'Not Found.'
      end  
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:title, :date, :content, :organization_id, :member_type, :committee_id)
    end

    def is_staff?
      unless current_user.role != 'Member'
        redirect_to root_path, notice: 'Access Denied'
      end
    end
    def is_admin?
      unless user_signed_in? && current_user.role == "Admin"
        redirect_to root_path, notice: 'Access Denied'
      end
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @announcement.errors.any? %>
    <strong><%= @announcement.errors.count %> errors detected.</strong>
    <ul>
    <% @announcement.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
    <!-- 
      <%= f.date_select :date, :class => 'form-control' %>
     -->
      <input type="text" id="date" name="announcement[date]" value= "<%= @announcement.date %>" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
      <%= f.text_area :content, :class => 'form-control', style: 'max-width: 100%;' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :organization_id, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
      <%= f.select( :organization_id, @organizations, {include_blank: 'Choose Organization'}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :member_type, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
      <%= f.select(:member_type, ["Student Member", "Associate Member", "Professional Member"], {include_blank: 'Choose Member Type'}, {class: "form-control"} ) %>
    </div>
  </div>
<!-- 
  <div class="form-group">
    <%= f.label :committee_id, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
      <%= f.select( :committee_id, Committee.all.collect{|o| [o.name, o.id]}, {include_blank: 'Choose Committee'}, {class: "form-control"}) %>
    </div>
  </div> -->

  <div class="form-actions">
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                announcements_path, :class => 'btn' %>
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>


<script>
  $(document).ready(function() {
      $( "#date" ).datepicker({
        dateFormat: "dd-mm-yy"
      });
      $( "#date" ).datepicker( "setDate", new Date());
  });
</script>

app/views/announcements/edit.html.erb
<%- model_class = Announcement -%>
<div class="">
  <h4><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h4>
</div>
<%= render :partial => 'form' %>

app/views/announcements/index.html.erb
<%- model_class = Announcement -%>
<div class="">
  <%= (link_to t('.new', :default => t("helpers.links.new")), new_announcement_path,
            :class => 'btn btn-primary btn-sm pull-right')  unless current_user.role == 'Member'  %>
  <h4><%=t '.title', :default => model_class.model_name.human.pluralize %> <small>(<%= @announcements.count || 0 %>) found.</small></h4>
</div>

<% if @announcements.present? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:title) %></th>
          <th><%= model_class.human_attribute_name(:date) %></th>
          <th><%= model_class.human_attribute_name(:committee) %></th>
          <th><%= model_class.human_attribute_name(:organization) %></th>
          <th><%= model_class.human_attribute_name(:member_type) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @announcements.each do |announcement| %>
          <tr>
            <td><%= announcement.title %></td>
            <td><%= announcement.date %></td>
            <td><%= announcement.committee.name if announcement.committee.present? %></td>
            <td><%= announcement.organization.organization_name if announcement.organization.present? %></td>
            <td><%= announcement.member_type %></td>
            <td>
              <%= link_to 'Show', announcement_path(announcement), class: "btn btn-xs" %>
            <% unless current_user.role == "Member" %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_announcement_path(announcement), :class => 'btn btn-primary btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")), announcement_path(announcement), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs' if current_user.role == 'Admin' %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
    <br/>
    <div class="alert alert-info">No data found.</div>
<% end -%>

app/views/announcements/new.html.erb
<%- model_class = Announcement -%>
<div class="">
  <h4><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h4>
</div>
<%= render :partial => 'form' %>

app/views/announcements/show.html.erb
<%- model_class = Announcement -%>
<div class="">
  <h4><%=t '.title', :default => model_class.model_name.human %></h4>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @announcement.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @announcement.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @announcement.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:organization) %>:</strong></dt>
  <dd><%= @announcement.organization.organization_name if @announcement.organization.present? %></dd>
  <!-- 
  <dt><strong><%= model_class.human_attribute_name(:committee) %>:</strong></dt>
  <dd><%= @announcement.committee.name if @announcement.committee.present? %></dd>
   -->
  <dt><strong><%= model_class.human_attribute_name(:member_type) %>:</strong></dt>
  <dd><%= @announcement.member_type %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              announcements_path, :class => 'btn'  %>
        <% unless current_user.role == "Member" %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_announcement_path(@announcement), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")), announcement_path(@announcement), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' if current_user.role == "Admin" %>
        <% end %>
</div>