config/routes.rb
Rails.application.routes.draw do
	
  resources :degrees
  resources :photos
  # dashboard links for member

  # CSV Exports for ecmembers, committee members, members
  get "/export-ecmembers" => 'ecmembers#csv_export', as: 'csv_export_ecmembers'
  get "/export-committee_members" => 'committee_members#csv_export', as: 'csv_export_committee_members'
  get "/export-members" => 'members#csv_export', as: 'csv_export_members'


  get "/d/announcements" => "dashboard#announcements"
  get "/d/announcement/:id" => "dashboard#announcement", as: 'd_announcement'
  get "/d/attachments" => "dashboard#attachments"
  get "/d/attachment/:id" => "dashboard#attachment", as: 'd_attachment'
  get "/d/members" => "dashboard#members"
  get "/d/member_information" => "dashboard#member"
  get "/d/organizations" => "dashboard#organizations"
  get "/d/ecmembers" => "dashboard#ecmembers"
  get "/d/committees" => "dashboard#committees"
  get "/d/committee_members" => "dashboard#committee_members"



  # Edit password only
  get '/users/edit_information' => "users#edit_information", as: 'user_edit_information'
  post '/users/update_information' => "users#update_information", as: 'user_update_information'


  post '/users' => 'users#create'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }, path_names: {sign_up: 'creating_an_account_is_not_an_option' }
  
  resources :api_keys
  resources :announcements

  resources :committee_members
  resources :ecmembers
  resources :members
  resources :users
  
  resources :membership_applications
  resources :memberships
  resources :attachments
  resources :requests
  
  resources :committees
  resources :organizations

  # resources :access_controls
  # resources :permissions
  # resources :events
  # resources :member_data
  # resources :comittees
  
  get '/apply' => 'membership_applications#new', as: 'new_application'
	
  resources :states
  resources :townships
  resources :staffs

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # township populated when state is chosen
  get '/state_search' => 'membership_applications#state_search', as: 'state_search'

  # Email and role populated according to staff or member id in user form
  get '/populate_by_staff_id' => 'users#populate_by_staff_id', as: 'populate_by_staff_id'
  get '/populate_by_member_id' => 'users#populate_by_member_id', as: 'populate_by_member_id'

  root to: 'dashboard#index' 
  get 'index.xlsx' => 'members#export_excel'



  # Extend/Upgrade membership
  get '/memberships/:id/upgrade' => 'memberships#upgrade', as: 'upgrade_membership'
  post '/memberships/:id/upgrade' => 'memberships#upgraded'
  get '/memberships/:id/extend' => 'memberships#extend', as: 'extend_membership'
  post '/memberships/:id/extend' => 'memberships#extended'

  get 'requests/:id/accept' => 'requests#accept', as: 'accept_request'
  get 'requests/:id/reject' => 'requests#reject', as: ''

  get '/reports' => "report#index", as: 'report'

  get '/successful' => "membership_applications#successful"
  get '/accept/:id' => "membership_applications#accept", as: 'accept_membership_application_request'
  get '/reject/:id' => "membership_applications#reject", as: 'reject_membership_application_request'
  get '/done' => "membership_applications#done"
 
# CSV import for existing member list for each organization
  get '/csv_import' => 'members#csv_import', as: "csv_import"
  post '/member_list_csv_import' => 'members#member_list_csv_import', as: "member_list_csv_import"


# API key and Api 
  get '/display' => 'api_version1#display'
  get '/access_control/:id' => 'api_version1#access_control'
  get '/announcement/:id' => 'api_version1#announcement'
  get '/attachment/:id' => 'api_version1#attachment'


  get '/ecmember/:id' => 'api_version1#ecmember'
  get '/event/:id' => 'api_version1#event'
  get '/member_datum/:id' => 'api_version1#member_datum'
  get '/member/:id' => 'api_version1#member'
  get '/membership_application/:id' => 'api_version1#membership_application'
  get '/membership/:id' => 'api_version1#membership'
  get '/organization/:id' => 'api_version1#organization'

  get '/staff/:id' => 'api_version1#staff'
  get '/state/:id' => 'api_version1#state'
  get '/township/:id' => 'api_version1#township'
  get '/user/:id' => 'api_version1#user'


  get '/member_info_edit' => "members#member_info_edit"
  post '/member_info_edit' => "members#member_info_update"


  get '/member_search' => "ecmembers#member_search"


  get "/organization_lvl_report" => "report#organization_lvl_report"
end

app/models/membership_application.rb
class MembershipApplication < ApplicationRecord
	validates_presence_of :name, :phone, :email, :member_type, :state#, :dob, :father_name, :address, :township, :highest_education, :gender#, :nrc, :ref_no, :certificates, :areas_of_training, :efficiencies, :current_employment, :employment_history, :areas_of_professional_working_experiences, :application_status, :process_status, :certificates, :current_employment, :employment_history
	mmunicode_convert :burmese_name

	has_many :attachments
	has_many :photos
	has_many :degrees
	has_one :member
	# belongs_to :member, optional: true

	NRC_INITIAL_OPTIONS = [1,2,4,5,6,7,8,9,10,11,12,13,14]
	NRC_MIDDLE_OPTIONS = ["နိုင်", "ဧည့်", "ပြု"]
	NRC_MIDDLE_OPTIONS = ["Naing", "Ae", "Pyu"]


	validates_uniqueness_of :nrc_no, scope: [:nrc_initial, :nrc_tsp]
	validate :set_nrc

	def set_nrc
		if nrc.blank?
			if nrc_tsp.blank?
				errors.add(:nrc_tsp, "can't be blank")
			elsif nrc_tsp.present?
				errors.add(:nrc_tsp, "must be letter") unless nrc_tsp =~ /[a-z A-Z]/
			end
			if nrc_no.blank?
				errors.add(:nrc_no, "can't be blank")
			end
			if nrc_middle.blank?
				errors.add(:nrc_middle, "can't be blank")
			end
			if nrc_initial.blank?
				errors.add(:nrc_initial, "can't be blank")
			end
		else
			# NRC is not initial/township(middle)number
		end
	end

    has_attached_file :profile, styles: { large: "600x800>", medium: "300x300>", thumb: "25x25#" }, default_url: "/images/:style/missing.png"

    validates_attachment :profile, optional: true,
      content_type: { content_type: %w(image/jpeg image/jpg image/png) },
      size: { in: 0..2.megabytes }

end

app/controllers/membership_applications_controller.rb
class MembershipApplicationsController < ApplicationController
    layout :custom_layout #"apply", only: [:new, :create, :successful]
    before_action :is_member_login?
    before_action :is_staff?, except: [:new, :create, :successful, :state_search, :done]
    before_action :set_membership_application, only: [:show, :edit, :update, :destroy, :accept, :reject]

    # GET /membership_applications
    # GET /membership_applications.json
    def index
        if current_user.role == "Admin"
            @membership_applications = MembershipApplication.all
        elsif current_user.staff.organization.organization_name == "Myanmar Computer Professionals Association"
            @membership_applications = MembershipApplication.all
        else
            @membership_applications = MembershipApplication.where("state LIKE ?", current_user.staff.organization.state.name)
        end

        date_search = Date.parse(params[:date_search]) unless params[:date_search].nil? || params[:date_search].blank?
        
        if params[:state_search].present?
            state_name = State.find(params[:state_search]).name
          @membership_applications = MembershipApplication.where(state: state_name)
        end

        if params[:search_by].present?
          @membership_applications = @membership_applications.where('lower(name) LIKE ? OR lower(phone) LIKE ? OR lower(email) LIKE ? OR lower(nrc) LIKE ?', "%#{params[:search_by].downcase}%", "%#{params[:search_by].downcase}%", "%#{params[:search_by].downcase}%", "%#{params[:search_by].downcase}%") if params[:search_by].to_i == 0
        end
        if params[:date_search].present? || params[:grade_search].present? || params[:organization_search].present?
            if params[:date_search].present?
              @membership_applications = @membership_applications.where('DATE(created_at) <= ?', date_search)
            end
            if params[:grade_search].present?
              # params[:grade_search] is the value of the grade in the membership, not the id of the membership
              @membership_applications = @membership_applications.where('member_type = ?', "#{params[:grade_search]}")
            end
        end
        @membership_applications = @membership_applications.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
    end

    # GET /membership_applications/1
    # GET /membership_applications/1.json
    def show
    end

    # GET /membership_applications/new
    def new
        @membership_application = MembershipApplication.new
        @townships = Township.all
    end

    # GET /membership_applications/1/edit
    def edit
        @townships = Township.all
    end

    # POST /membership_applications
    # POST /membership_applications.json
    def create
        respond_to do |format|
            @membership_application = MembershipApplication.new(membership_application_params)
            if  User.find_by_email(@membership_application.email).present?
                @error = "Email already occupied."
                format.html { render :new}
                format.json { render json: @membership_application.errors, status: :unprocessable_entity }
            else
                highest_education = ""
                certificates = {}
                areas_of_training = []
                efficiencies = []
                current_employment = {}
                employment_history = {}
                areas_of_professional_working_experiences = []

                # For highest_education
                highest_education = params[:highest_education] if params[:highest_education].present?
                # For highest_education

                # For Certificates
                    if params[:education1].present? && params[:date1].present? && params[:institution1].present?
                        certificates[:certificate1] = { :education => "#{params[:education1]}", :date =>  "#{params[:date1]}", :institution => "#{params[:institution1]}"}

                        if params[:education2].present? && params[:date2].present? && params[:institution2].present?
                            certificates[:certificate2] = { :education => "#{params[:education2]}", :date =>  "#{params[:date2]}", :institution => "#{params[:institution2]}"}
                        end
                        if params[:education3].present? && params[:date3].present? && params[:institution3].present?
                            certificates[:certificate3] = { :education => "#{params[:education3]}", :date =>  "#{params[:date3]}", :institution => "#{params[:institution3]}"}
                        end
                        if params[:education4].present? && params[:date4].present? && params[:institution4].present?
                            certificates[:certificate4] = { :education => "#{params[:education4]}", :date =>  "#{params[:date4]}", :institution => "#{params[:institution4]}"}
                        end
                        if params[:education5].present? && params[:date5].present? && params[:institution5].present?
                            certificates[:certificate5] = { :education => "#{params[:education5]}", :date =>  "#{params[:date5]}", :institution => "#{params[:institution5]}"}
                        end
                    end
                # For Certificates

                # For areas_of_training
                    areas_of_training[0] = params[:training_programming] unless params[:training_programming].blank? || params[:training_programming].nil?
                    areas_of_training[1] = params[:training_software_engineering] unless params[:training_software_engineering].blank? || params[:training_software_engineering].nil?
                    areas_of_training[2] = params[:training_database] unless params[:training_database].blank? || params[:training_database].nil?
                    areas_of_training[3] = params[:training_networking] unless params[:training_networking].blank? || params[:training_networking].nil?
                    areas_of_training[4] = params[:training_web_development] unless params[:training_web_development].blank? || params[:training_web_development].nil?
                    areas_of_training[5] = params[:training_operation_system] unless params[:training_operation_system].blank? || params[:training_operation_system].nil?
                    areas_of_training[6] = params[:training_graphic_design] unless params[:training_graphic_design].blank? || params[:training_graphic_design].nil?
                    areas_of_training[7] = params[:training_multimedia] unless params[:training_multimedia].blank? || params[:training_multimedia].nil?
                    areas_of_training[8] = params[:training_hardware] unless params[:training_hardware].blank? || params[:training_hardware].nil?
                    areas_of_training[9] = params[:training_mis] unless params[:training_mis].blank? || params[:training_mis].nil?
                # For areas_of_training

                # For efficiencies
                    efficiencies[0] = params[:efficiencies_pascal] unless params[:efficiencies_pascal].blank? || params[:efficiencies_pascal].nil? 
                    efficiencies[1] = params[:efficiencies_cobol] unless params[:efficiencies_cobol].blank? || params[:efficiencies_cobol].nil? 
                    efficiencies[2] = params[:efficiencies_assembly] unless params[:efficiencies_assembly].blank? || params[:efficiencies_assembly].nil? 
                    efficiencies[3] = params[:efficiencies_c_c_plus_plus] unless params[:efficiencies_c_c_plus_plus].blank? || params[:efficiencies_c_c_plus_plus].nil? 
                    efficiencies[4] = params[:efficiencies_basic] unless params[:efficiencies_basic].blank? || params[:efficiencies_basic].nil? 
                    efficiencies[5] = params[:efficiencies_visual_basic] unless params[:efficiencies_visual_basic].blank? || params[:efficiencies_visual_basic].nil? 
                    efficiencies[6] = params[:efficiencies_visual_c] unless params[:efficiencies_visual_c].blank? || params[:efficiencies_visual_c].nil? 
                    efficiencies[7] = params[:efficiencies_java] unless params[:efficiencies_java].blank? || params[:efficiencies_java].nil? 
                    efficiencies[8] = params[:efficiencies_net] unless params[:efficiencies_net].blank? || params[:efficiencies_net].nil? 
                    efficiencies[9] = params[:efficiencies_asp] unless params[:efficiencies_asp].blank? || params[:efficiencies_asp].nil? 
                    efficiencies[10] = params[:efficiencies_perl] unless params[:efficiencies_perl].blank? || params[:efficiencies_perl].nil? 
                    efficiencies[11] = params[:efficiencies_php] unless params[:efficiencies_php].blank? || params[:efficiencies_php].nil? 
                    efficiencies[12] = params[:efficiencies_jsp] unless params[:efficiencies_jsp].blank? || params[:efficiencies_jsp].nil? 
                    efficiencies[13] = params[:efficiencies_cold_fusion] unless params[:efficiencies_cold_fusion].blank? || params[:efficiencies_cold_fusion].nil? 
                    efficiencies[14] = params[:efficiencies_html] unless params[:efficiencies_html].blank? || params[:efficiencies_html].nil? 
                    efficiencies[15] = params[:efficiencies_linux] unless params[:efficiencies_linux].blank? || params[:efficiencies_linux].nil? 
                    efficiencies[16] = params[:efficiencies_windows] unless params[:efficiencies_windows].blank? || params[:efficiencies_windows].nil? 
                    efficiencies[17] = params[:efficiencies_apple] unless params[:efficiencies_apple].blank? || params[:efficiencies_apple].nil? 
                    efficiencies[18] = params[:efficiencies_unix] unless params[:efficiencies_unix].blank? || params[:efficiencies_unix].nil? 
                    efficiencies[19] = params[:efficiencies_database] unless params[:efficiencies_database].blank? || params[:efficiencies_database].nil? 

app/helpers/membership_applications_helper.rb
module MembershipApplicationsHelper
end

app/views/membership_applications/_township_populate.html.erb
<div id="town_select">
<%= select_tag "township", options_from_collection_for_select(@townships, "name", "name"), {include_blank: 'Choose Township', class: 'form-control input-sm'} %>
</div>

app/views/membership_applications/done.html.erb
<h4 align="center">Thank you for your registration.</h4>
<p>We will send an email.</p>

app/views/membership_applications/edit.html.erb
<%- model_class = MembershipApplication -%>
<div class="">
  <h4><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                               :default => "Edit MCPA #{model_class.model_name.human}") %></h4>
</div>
<%= render :partial => 'form' %>

app/views/membership_applications/index.html.erb
<%- model_class = MembershipApplication -%>
<div class="">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_membership_application_path,
              :class => 'btn btn-primary btn-sm pull-right' %>
  <h4><%=t '.title', :default => model_class.model_name.human.pluralize %> <small>(<%= @membership_applications.count || 0 %>) found.</small></h4>
</div>
    <div class="alert alert-warning">Click the 'FILTER' button.</div>
    <div style="margin-bottom: -15px;" >
        <div class="row hidden-xs">
            <%= form_tag "/membership_applications", method: 'get' do %>
                <div class="col-sm-4">
                    <%= text_field_tag :search_by, params[:search_by], placeholder: 'Name/Phone/Email/NRC', autocomplete: :off, class: 'form-control input-sm' %>
                </div>
                <div class="col-sm-3">
                    <input type="text" id="date_search" name="date_search" class="form-control input-sm" placeholder="Apply Before the date" >
                </div>
                <div class="col-sm-2">
                    <%= select_tag 'grade_search', options_for_select(["Associate Member", "Student Member", "Professional Member", "Fellow Member"]), {:class => 'form-control input-sm', include_blank: 'Choose Grade'} %>
                </div>
                <% if current_user.role == "Admin" %>
                    <div class="col-sm-2">
                        <%= select_tag 'state_search', options_from_collection_for_select(State.all, :id, :name), {:class => 'form-control input-sm', include_blank: 'Choose State'} %>
                    </div>
                <% end -%>
                <div class="col-sm-1 pull-right">
                    <%= submit_tag "Filter", :name=> nil, class: "btn btn-primary btn-sm pull-right" %>
                    <br/>
                </div>
            <% end %>
        </div>
    </div>
        <% if @membership_applications.present? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:member_type) %></th>
      <th><%= model_class.human_attribute_name(:highest_education) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @membership_applications.each do |membership_application| %>
      <tr>
        <td><%= membership_application.name %></td>
        <td><%= membership_application.email %></td>
        <td><%= membership_application.phone %></td>
        <td><%= membership_application.member_type %></td>
        <td><%= membership_application.highest_education %></td>
        <td><%= membership_application.state %></td>
        <td>
          <% unless membership_application.member.present? %>
            <%= link_to "Accept", accept_membership_application_request_url(membership_application), :class => 'btn btn-xs' %>
            <!-- <%= link_to "Reject", reject_membership_application_request_url(membership_application), :class => 'btn btn-xs' %> -->
          <% end %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      membership_application_path(membership_application), :class => 'btn btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_membership_application_path(membership_application), :class => 'btn btn-primary btn-xs'  if current_user.role == "Admin" %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")), membership_application_path(membership_application), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs' if current_user.role == "Admin" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div align="center">
  <%= will_paginate @membership_applications %>
</div>
      <% else %>
      <br/>
<div class="alert alert-info">No data found.</div>
      <% end -%>

<script type="text/javascript">
    $(document).ready(function() {

        $( "#date_search" ).datepicker({
            // changeMonth: true,
            // changeYear: true,
            // yearRange: '2017:2050',
            dateFormat: "dd-mm-yy"
        });
    });
</script>

app/views/membership_applications/new.html.erb
<%- model_class = MembershipApplication -%>
<div class="page-header">
  <%= image_tag 'mcpa_logo', style: "width:80px;", class:"pull-right" %> 
  <h4><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                :default => "New Membership Application") %></h4>
</div>
<%= render :partial => 'form' %>

app/views/membership_applications/show.html.erb
<%- model_class = MembershipApplication -%>
<div class="">
  <h4><%=t '.title', :default => model_class.model_name.human %></h4>
</div>

<div class="col-lg-6 col-md-6">
  <dl class="dl-horizontal">
    <h6>1. PERSONAL INFORMATION</h6>
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @membership_application.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:burmese_name) %>:</strong></dt>
    <dd><%= @membership_application.burmese_name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
    <dd><%= @membership_application.gender %></dd>
    <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
    <dd><%= @membership_application.dob %></dd>
    <dt><strong><%= model_class.human_attribute_name(:nrc) %>:</strong></dt>
    <dd><%= @membership_application.nrc_initial %>/<%= @membership_application.nrc_tsp %>(<%= @membership_application.nrc_middle %>)<%= @membership_application.nrc_no %></dd>
    <dt><strong><%= model_class.human_attribute_name(:father_name) %>:</strong></dt>
    <dd><%= @membership_application.father_name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
    <dd><%= @membership_application.address %></dd>
    <dt><strong><%= model_class.human_attribute_name(:township) %>:</strong></dt>
    <dd><%= @membership_application.township %></dd>
    <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
    <dd><%= @membership_application.state %></dd>
    <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
    <dd><%= @membership_application.phone %></dd>
    <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
    <dd><%= @membership_application.email %></dd>
    <dt><strong><%= model_class.human_attribute_name(:member_type) %>:</strong></dt>
    <dd><%= @membership_application.member_type %></dd>
  </dl>
</div>

<div class="col-lg-6 col-md-6">
  <dl class="dl-horizontal">

    <h6>2. EDUCATION INFORMATION</h6>
    <dt><strong><%= model_class.human_attribute_name(:highest_education) %>:</strong></dt>
    <dd><%= @membership_application.highest_education %></dd>
    <dt><strong><%= model_class.human_attribute_name(:certificates) %>:</strong></dt>
    <dd>
    <% if @membership_application.certificates.present? %>
      <%- @membership_application.certificates.each do |key, value| -%>
        <strong><%= key %></strong>
        <% value.each do |k, v| %>
          <%= k %> : <%= v %> | 
        <% end %>
        <br/>
      <%- end -%>
    <% end %>
    </dd>
    <dt><strong><%= model_class.human_attribute_name(:areas_of_training) %>:</strong></dt>
    <dd><%= @membership_application.areas_of_training.compact if @membership_application.areas_of_training.present? %></dd>
    <dt><strong><%= model_class.human_attribute_name(:efficiencies) %>:</strong></dt>
    <dd><%= @membership_application.efficiencies.compact if @membership_application.efficiencies.present? %></dd>
    </dl>
</div>

<div class="col-xs-12">
  <dl class="dl-horizontal">
    <h6>3. EMPLOYMENT INFORMATION</h6>
    <dt><strong><%= model_class.human_attribute_name(:current_employment) %>:</strong></dt>
    <dd>
    <% if @membership_application.current_employment.present? %>
      <%- @membership_application.current_employment.each do |key, value| -%>
        <strong><%= key %></strong> : <%= value %><br/>
      <%- end -%>
    <% end %>
    </dd>
    <dt><strong><%= model_class.human_attribute_name(:employment_history) %>:</strong></dt>
    <dd>
    <% if @membership_application.employment_history.present? %>
      <%- @membership_application.employment_history.each do |key, value| -%>
        <strong><%= key %> </strong>
        <% value.each do |k, v| %>
          <%= k %> : <%= v %> | 
        <% end %>
        <br/>
      <%- end -%>
    <% end %>
    </dd>
    <dt><strong><%= model_class.human_attribute_name(:areas_of_professional_working_experiences) %>:</strong></dt>
    <dd><%= @membership_application.areas_of_professional_working_experiences.compact if @membership_application.areas_of_professional_working_experiences.present? %></dd>
  </dl>
</div>

<div class="col-xs-12">
  <% if @membership_application.attachments.present? %>
      <%- @membership_application.attachments.each do |attachment| -%>
      <div class="col-md-4 col-sm-6">
        <%= image_tag attachment.file_attachment.url(:small) %><br/>
        <strong><%=  attachment.attachment_type%></strong>
      </div>
      <% end -%>
    <% end %>
</div>

<div class="form-actions col-xs-12">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              membership_applications_path, :class => 'btn'  %>
  <% unless @membership_application.member.present? %>
    <%= link_to "Accept", accept_membership_application_request_url(@membership_application), :class => 'btn ' %>
    <!-- <%= link_to "Reject", reject_membership_application_request_url(@membership_application), :class => 'btn ' %> -->
  <% end %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_membership_application_path(@membership_application), :class => 'btn btn-primary' if current_user.role == "Admin" %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              membership_application_path(@membership_application), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' if current_user.role == "Admin" %>

</div>
  <div class="container"><br/></div>
<br/>

app/views/membership_applications/state_search.html.erb
<div id="town_select">
<%= select_tag "township]", options_from_collection_for_select(@townships, "id", "name"), {include_blank: 'Choose Township', class: 'form-control input-sm'} %>
<%= @townships.inspect %>
<%= @townships.count %>
<%= @townships.ids %>
</div>

app/views/membership_applications/state_search.js.erb
$('#membership_application_township').html("<%= j render 'township_populate' %>");

app/views/membership_applications/successful.html.erb
<div class="page-header">
  <%= image_tag 'mcpa_logo', style: "width:80px;", class:"pull-right" %> 
  <h4>Myanmar Computer Professionals Association</h4>
</div>
<div class="col-md-12">
	<p>Your membership is successfully applied. Please upload required attachments later.</p>
	<p>Your password is <%= @password %>. Please change it after you login.</p>
	<p><%= link_to "Add Attachment", "/attachments/new?membership_application_ref_no=#{@membership_application.ref_no}" %> for the attachment</p>
	<br/>
</div>