config/routes.rb
Rails.application.routes.draw do
	
  resources :degrees
  resources :photos
  # dashboard links for member

  # CSV Exports for ecmembers, committee members, members
  get "/export-ecmembers" => 'ecmembers#csv_export', as: 'csv_export_ecmembers'
  get "/export-committee_members" => 'committee_members#csv_export', as: 'csv_export_committee_members'
  get "/export-members" => 'members#csv_export', as: 'csv_export_members'


  get "/d/announcements" => "dashboard#announcements"
  get "/d/announcement/:id" => "dashboard#announcement", as: 'd_announcement'
  get "/d/attachments" => "dashboard#attachments"
  get "/d/attachment/:id" => "dashboard#attachment", as: 'd_attachment'
  get "/d/members" => "dashboard#members"
  get "/d/member_information" => "dashboard#member"
  get "/d/organizations" => "dashboard#organizations"
  get "/d/ecmembers" => "dashboard#ecmembers"
  get "/d/committees" => "dashboard#committees"
  get "/d/committee_members" => "dashboard#committee_members"



  # Edit password only
  get '/users/edit_information' => "users#edit_information", as: 'user_edit_information'
  post '/users/update_information' => "users#update_information", as: 'user_update_information'


  post '/users' => 'users#create'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }, path_names: {sign_up: 'creating_an_account_is_not_an_option' }
  
  resources :api_keys
  resources :announcements

  resources :committee_members
  resources :ecmembers
  resources :members
  resources :users
  
  resources :membership_applications
  resources :memberships
  resources :attachments
  resources :requests
  
  resources :committees
  resources :organizations

  # resources :access_controls
  # resources :permissions
  # resources :events
  # resources :member_data
  # resources :comittees
  
  get '/apply' => 'membership_applications#new', as: 'new_application'
	
  resources :states
  resources :townships
  resources :staffs

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # township populated when state is chosen
  get '/state_search' => 'membership_applications#state_search', as: 'state_search'

  # Email and role populated according to staff or member id in user form
  get '/populate_by_staff_id' => 'users#populate_by_staff_id', as: 'populate_by_staff_id'
  get '/populate_by_member_id' => 'users#populate_by_member_id', as: 'populate_by_member_id'

  root to: 'dashboard#index' 
  get 'index.xlsx' => 'members#export_excel'



  # Extend/Upgrade membership
  get '/memberships/:id/upgrade' => 'memberships#upgrade', as: 'upgrade_membership'
  post '/memberships/:id/upgrade' => 'memberships#upgraded'
  get '/memberships/:id/extend' => 'memberships#extend', as: 'extend_membership'
  post '/memberships/:id/extend' => 'memberships#extended'

  get 'requests/:id/accept' => 'requests#accept', as: 'accept_request'
  get 'requests/:id/reject' => 'requests#reject', as: ''

  get '/reports' => "report#index", as: 'report'

  get '/successful' => "membership_applications#successful"
  get '/accept/:id' => "membership_applications#accept", as: 'accept_membership_application_request'
  get '/reject/:id' => "membership_applications#reject", as: 'reject_membership_application_request'
  get '/done' => "membership_applications#done"
 
# CSV import for existing member list for each organization
  get '/csv_import' => 'members#csv_import', as: "csv_import"
  post '/member_list_csv_import' => 'members#member_list_csv_import', as: "member_list_csv_import"


# API key and Api 
  get '/display' => 'api_version1#display'
  get '/access_control/:id' => 'api_version1#access_control'
  get '/announcement/:id' => 'api_version1#announcement'
  get '/attachment/:id' => 'api_version1#attachment'


  get '/ecmember/:id' => 'api_version1#ecmember'
  get '/event/:id' => 'api_version1#event'
  get '/member_datum/:id' => 'api_version1#member_datum'
  get '/member/:id' => 'api_version1#member'
  get '/membership_application/:id' => 'api_version1#membership_application'
  get '/membership/:id' => 'api_version1#membership'
  get '/organization/:id' => 'api_version1#organization'

  get '/staff/:id' => 'api_version1#staff'
  get '/state/:id' => 'api_version1#state'
  get '/township/:id' => 'api_version1#township'
  get '/user/:id' => 'api_version1#user'


  get '/member_info_edit' => "members#member_info_edit"
  post '/member_info_edit' => "members#member_info_update"


  get '/member_search' => "ecmembers#member_search"


  get "/organization_lvl_report" => "report#organization_lvl_report"
end

app/models/attachment.rb
class Attachment < ApplicationRecord

	belongs_to :membership_application
	validates_presence_of :file_attachment,:membership_application_id
	
	has_attached_file :file_attachment, styles: { large: "600x800>", medium: "300x300>", small: "150x150>" }, default_url: "/images/:style/missing.png"

	validates_attachment :file_attachment, presence: true,
	  content_type: { content_type: %w(image/jpeg image/jpg image/png application/pdf) },
	  size: { in: 0..2.megabytes }
	# Validate filename
	# validates_attachment_file_name :file_attachment, matches: [/png\z/, /jpe?g\z/, /pdf\z/]
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  layout :custom_layout#"apply", only: [:new, :create]
  before_action :is_login?, except: [:show, :new, :create]
  before_action :is_admin?, only: [:destroy]
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    if user_signed_in? && current_user.role != 'Member'

      @attachments = Attachment.all
      @attachments = @attachments.joins(:membership_application).where("lower(name) LIKE ?", "%#{params[:search_by].downcase}%") if params[:search_by].present?
        @attachments = @attachments.where("attachment_type = ? ", params[:search_attachment_type]) if params[:search_attachment_type].present?
    else
      @membership_application = current_user.member.membership_application
      @attachments = @membership_application.present? ? @membership_application.attachments : Attachment.where("id = 0")
    end

    @attachments = @attachments.paginate(page: params[:page], per_page: 20)
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    unless user_signed_in?
      @ref_no = @attachment.membership_application.ref_no
    end
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
    if user_signed_in? && current_user.role == "Member"
      @member = current_user.member
      @membership = @member.memberships.last
      if @member.membership_application.present?
        @attachment.membership_application_id = @member.membership_application.id 
      else
        membership_application = MembershipApplication.new(name: @member.name, nrc: @member.nrc, email: @member.email, phone: @member.phone, address: @member.address, state: @member.state, township: @member.township, member_type: @membership.grade)
        membership_application.save(validate: false)
        @member.update(membership_application_id: membership_application.id)
        @attachment.membership_application_id = membership_application.id
      end
    else
      @attachment.membership_application_id = MembershipApplication.find_by_ref_no(params[:membership_application_ref_no]).id if params[:membership_application_ref_no].present? 
      # @member = Member.find_by_member_no(params[:membership_application_ref_no]) if params[:membership_application_ref_no].present?
    end
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)
    @attachment.membership_application_id = MembershipApplication.find_by_name(params[:attachment][:membership_application_id]).id unless user_signed_in? && current_user.role != "Member"

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to "/attachments/#{@attachment.id}?membership_application_ref_no=#{@attachment.membership_application.ref_no}", notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    @attachment.membership_application_id = MembershipApplication.find_by_name(params[:attachment][:membership_application_id]).id if current_user.role == 'Member'
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected
  def custom_layout
    if !user_signed_in? || (user_signed_in? && current_user.role == 'Member' && action_name == 'new')
      "apply"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      if user_signed_in?
        if current_user.role == 'Member'
            ### Member can see his own attachments
            attachments = current_user.member.membership_application.attachments
            if attachments.ids.include? (params[:id].to_i)
              @attachment = Attachment.find(params[:id])
            else
              redirect_to '/d/attachments', notice: "Not Found"
            end
        elsif current_user.role == "Staff"
            ### Staff can see the attachments of the members who belongs to corresponding organizations
            @attachment = Attachment.find(params[:id])
        else
            ### Admin can see all the attachments
            @attachment = Attachment.find(params[:id])
        end
      else
        @attachment = Attachment.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:membership_application_id, :file_attachment, :attachment_type)
    end

    # Check login
    def is_login?
      unless user_signed_in?
        redirect_to new_user_session_path
      else
        if current_user.role == 'Member'
          redirect_to '/d/attachments'
        end
      end
    end

    # Only staff can access this model
    def is_staff?
      unless user_signed_in? && current_user.role != "Member"
        redirect_to root_path, notice: 'Access Denied'
      end
    end
    def is_admin?
      unless user_signed_in? && current_user.role == "Admin"
        redirect_to root_path, notice: 'Access Denied'
      end
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
  <p class="notice"><%= @notice %></p>
  <%= form_for @attachment, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @attachment.errors.any? %>
      <strong><%= @attachment.errors.count %> errors detected.</strong>
      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    <% end %>
    <div class="row">
        <div class="form-group col-md-12">
          <%= f.label :membership_application_id, :class => 'control-label col-md-2' %>
          <div class="col-md-4">
            <% if user_signed_in? && current_user.role != "Member" %>
              <%= f.select(:membership_application_id, MembershipApplication.all.collect {|m| [m.name, m.id]}, { include_blank: 'Choose Membership Applicaion'}, {class: 'form-control'}) %>
            <% else %>
              <input type="text" id="attachment_membership_application" name="attachment[membership_application_id]" value="<%= @attachment.membership_application.name if @attachment.membership_application.present? %>" class="form-control" readonly>
            <% end %>
          </div>
        </div>
        <div class="form-group col-md-12">
          <%= f.label :file_attachment, :class => 'control-label col-md-2' %>
          <div class="col-md-4">
            <%= f.file_field :file_attachment, :class => 'form-control' %>
          </div>
        </div>
        <div class="form-actions col-md-12">
          <% if user_signed_in? %>
            <%= link_to "Back", :back, class: 'btn' %>
          <% elsif !@attachment.membership_application.attachments.present? %>
          <% end %>
          <%= f.submit nil, :class => 'btn btn-primary' %>
          <br/>
          <br/>
        </div>
    </div>
  <% end %>

app/views/attachments/edit.html.erb
<%- model_class = Attachment -%>
<div class="">
  <h4><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h4>
</div>
<%= render :partial => 'form' %>

app/views/attachments/index.html.erb
<%- model_class = Attachment -%>
<div class="">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_attachment_path, :class => 'btn btn-primary btn-sm pull-right' if user_signed_in? %>
  <h4><%=t '.title', :default => model_class.model_name.human.pluralize %> <small>(<%= @attachments.count || 0 %>) found.</small></h4>
</div>

<% if current_user.role != "Member" %>
    <div class="alert alert-warning">Click the 'FILTER' button.</div>
    <div class="row" style="margin-bottom: -15px;" >
        <%= form_tag '/attachments', method: 'get' do %>
            <div class="col-sm-5">
                <%= text_field_tag :search_by, params[:search_by], placeholder: 'Filter by Member Name', autocomplete: :off, class: 'form-control input-sm' %>
            </div>
            <div class="col-sm-4">
                  <%= select_tag :search_attachment_type, options_for_select(["Bank Payment Slip", "Picture", "Certificates"]), {include_blank: 'Choose Type', class: 'form-control input-sm'} %>
            </div>
            <div class="col-sm-1 pull-right">
                <%= submit_tag 'Filter', name: nil, class: "btn btn-primary btn-sm pull-right" %>
            </div>
        <% end %>
    </div>
<% end %>

<% if @attachments.present? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:membership_application_id) %></th>
          <th><%= model_class.human_attribute_name(:attachment_type) %></th>
          <th><%= model_class.human_attribute_name(:file_attachment) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @attachments.each do |attachment| %>
          <tr>
            <td><%= attachment.membership_application.name if attachment.membership_application.present? %></td>
            <td><%= attachment.attachment_type %></td>
            <td><%= image_tag attachment.file_attachment.url(:small) %></td>
            <td>
              <%= link_to t('.show', :default => t("helpers.links.show")),
                          attachment_path(attachment), :class => 'btn btn-xs' %>
            <% unless current_user.role == "Member" %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_attachment_path(attachment), :class => 'btn btn-primary btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")), attachment_path(attachment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs' if current_user.role == 'Admin' %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div align="center">
      <%= will_paginate @attachments%>
    </div>
<% else %>
    <br/>
    <div class="alert alert-info">No data found.</div>
<% end -%>

app/views/attachments/new.html.erb
<%- model_class = Attachment -%>
<div class="">
	<%= image_tag 'mcpa_logo', style: "width:80px;", class:"pull-right" %> 
	<% if user_signed_in? && current_user.role != "Member" %>
		<h4>New Attachment</h4>
	<% else %>
		<h4><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
            :default => "Bank Note for Membership application #{@attachment.membership_application.name if @attachment.membership_application.present? }") %></h4>
    <% end %>
</div>
<br/>
<div class="col-xs-12">
	<div class="row col-md-12" id="rule_and_regulation" hidden>
	    <div class="panel panel-default">
	    <div class="panel-heading">
	    <h5>အသင်းဝင်လိုသူများအတွက် စည်းကမ်းချက်များ</h5>
	    </div>
	    <div class="panel-body">
	    <p>
	        <h6>Student Member ဝင်ခွင့်ရသူများ</h6>
	        (ဝင်ကြေး - ၁,၅၀၀ ကျပ်၊ နှစ်စဉ်ကြေး - ၂,၀၀၀ ကျပ်)<br/>
	        ၁။  ကွန်ပျူတာတက္ကသိုလ်၊ နည်းပညာတက္ကသိုလ် (ပထမနှစ်၊ ဒုတိယနှစ်) တက်ရောက်နေသည့် ကျောင်းသား/ သူများ။<br/>
	        ၂။  မြန်မာနိုင်ငံကွန်ပျူတာပညာရှင်အသင်း အသိအမှတ်ပြုသည့် ကေျာင်း၊ အဖွဲ့အစည်းမှ ဖွင့် လှစ်သော IT Diploma သင်တန်း၊ International IT Diploma သင်တန်းတက်ရောက်ဆဲ ကျောင်းသား/သူများ။<br/>
	        ၃။  MCPA မှ အသိအမှတ်ပြုထားသည့် သင်တန်းများတွင် IT Professional Certification Course ကိုအနည်းဆုံး နာရီ(၁၂၀) တက်ရောက်ပြီးသူများ။<br/>
	    </p>
	    <p>
	        
	        <h6>Associate Member ဝင်ခွင့်ရသူများ</h6>
	        (ဝင်ကြေး - ၃,၀၀၀ ကျပ်၊ နှစ်စဉ်ကြေး - ၄,၀၀၀ ကျပ်)<br/>
	        ကွန်ပျူတာပညာဖြင့် အသက်မွေး၀မ်းကြောင်းပြုနေသူဖြစ်ပြီး အောက်ပါအရည်အချင်းများအနက် တစ်ခုခုနှင့် ကိုက်ညီလျှင် အသင်းသားရေးရာကော်မတီက လက်ခံစစ်ဆေးပြီး ခွင့်ပြုခြင်း/ ငြင်းပယ်ခြင်း ပြုလုပ်နိုင်သည်။<br/>
	        ၁။  International Advanced Diploma (2) Years လက်မှတ်ရရှိထားသူများ။<br/>
	        ၂။  International Professional Certification from Vendors (eg. MCSA, MCSD, ……..) လက်မှတ်ရရှိသူများ။<br/>
	        ၃။  မြန်မာနိုင်ငံကွန်ပျူတာပညာရှင်အသင်း အသိအမှတ်ပြုသည့် ကေျာင်း၊ အဖွဲ့အစည်းမှ ဖွင့်လှစ်သော IT Diploma အောင်မြင်ပြီးသူများ၊ MCPA မှ စစ်ဆေးသော MCPA Exam ကို အောင်မြင်ပြီးသူများ။<br/>
	        ၄။  ကွန်ပျူတာတက္ကသိုလ်၊ နည်းပညာတက္ကသိုလ်၊ စက်မှုတက္ကသိုလ်တို့တွင် တတိယနှစ်နှင့် အထက် တက်ရောက်နေသည့် ကျောင်းသား/ သူများ။<br/>
	        ၅။  ကွန်ပျူတာပညာရှင်အဖြစ် အနည်းဆုံး (၂) နှစ် လုပ်ကိုင်ခဲ့ကြောင်း ကုမ္ပဏီ (သို့မဟုတ်) AM အသင်းသား (သို့မဟုတ်) PM အသင်းသား (သို့မဟုတ်) မိမိ၏ ဆောင်ရွက်ပေးခဲ့/ ပေးလျက် ရှိသော အဖွဲ့အစည်း တစ်ခုခုမှ ထောက်ခံစာပါရှိရမည်။ <br/>

	    </p><p>
	        <h6>Professional Member ဝင်ခွင့်ရသူများ</h6>
	        (ဝင်ကြေး - ၄,၀၀၀ ကျပ်၊ နှစ်စဉ်ကြေး - ၆,၀၀၀ ကျပ်)<br/>
	        ကွန်ပျူတာပညာဖြင့် အသက်မွေးဝမ်းကြောင်း ပြုနေသူဖြစ်ပြီး အောက်ပါအရည်အချင်းများအနက် တစ်ခုခုနှင့် ကိုက်ညီလျှင် အသင်းသားရေးရာကော်မတီက လက်ခံစစ်ဆေးပြီး ခွင့်ပြုခြင်း/ ငြင်းပယ်ခြင်း ပြုလုပ်နိုင်သည်။<br/>
	        ၁။  AM သက်တမ်း (၂) နှစ်ကြာမြင့်ပြီး ကွန်ပျူတာပညာရှင်အဖြစ် ဆက်လက်လုပ်ကိုင်နေသူများ။<br/>
	        ၂။  ကွန်ပျူတာတက္ကသိုလ်၊ နည်းပညာတက္ကသိုလ်၊ စက်မှုတက္ကသိုလ်တို့မှ ဘွဲ့ရရှိပြီး လုပ်သက် (၂) နှစ် ကေျာ်ရှိသူများ။<br/>
	        ၃။  ကွန်ပျူတာပညာရှင်အဖြစ် အနည်းဆုံး (၂) နှစ်လုပ်ကိုင်ခဲ့ကြောင်း ကုမ္ပဏီ (သို့မဟုတ်) PM အသင်းသား (သို့မဟုတ်) မိမိ၏ ဆောင်ရွက်ပေးခဲ့/ ပေးလျက်ရှိသော အဖွဲ့အစည်းတစ်ခုခုမှ ထောက်ခံစာပါရှိရမည်။<br/>
	        ၄။  အသင်းအလုပ်အမှုဆောင် အစည်းအဝေးမှ ဆုံးဖြတ်ချက်ဖြင့် အသင်းအတွက် ကူညီပံ့ပိုးနိုင်သော အရည်အချင်းရှိသူများ။<br/>

	    </p><p>
	        <h6>Fellow Member ဝင်ခွင့်ရသူများ</h6>
	        (အဆင့်မြှင့်ကြေး- ၁၀၀,၀၀၀ ကျပ်၊ နှစ်စဉ်ကြေး - မရှိ)<br/>
	        အောက်ဖော်ပြပါ ပုဂ္ဂိုလ်များသည် အသင်းသို့ အဆိုပြုလျှောက်ထားနိုင်ပြီး အလုပ်အမှုဆောင်အဖွဲ့ အစည်းအဝေးမှ ဆုံးဖြတ်မည်။<br/>
	        ၁။  PM ဖြစ်ပြီး MCPA အသင်းတွင် အလုပ်အမှုဆောင် သက်တမ်းပြည့် (၁)ကြိမ် တာဝန်ထမ်းဆောင် ပြီးသူများ။<br/>
	        ၂။  တက္ကသိုလ်၊ ကောလိပ်များမှ IT ကွန်ပျူတာဌာနတစ်ခုခု၏ တွဲဖက်ပါမောက္ခရာထူးနှင့် အထက် တာဝန်ထမ်းဆောင်ခဲ့သူ/ တာဝန်ထမ်းဆောင်နေသူများ။<br/>
	        ၃။  PM သက်တမ်း (၁၀) နှစ်ပြည့်ပြီးသူများ။<br/>

	    </p><p>
	        <h6>Honorary Member ဝင်ခွင့်ရသူများ</h6>
	        (ဝင်ကြေး - မရှိ)<br/>
	        ၁။  မြန်မာနိုင်ငံအတွင်းကွန်ပျူတာပညာနှင့် အသုံးချမှုဖွံ့ဖြိုးပြန့်ပွားရေးအတွက် ထူးခြားစွာ ကူညီထောက်ပံ့သူ / ပံ့ပိုးပေးသူ။ (အလုပ်အမှုဆောင် အစည်းအဝေးဆုံးဖြတ်ချက်ဖြင့် ပေးအပ်ရန်။)<br/>

	    </p>
	    </div>
	    </div>
	</div>
	<input type="button" id="btn_rnr" value="Read Rules And Regulations" class="row btn-primary pull-right" />
</div>
<div class="row col-xs-12">
	<strong>Upload the bank note for the membership.</strong>
	<%= render :partial => 'form' %>
</div>
<script>
$(document).ready(function() {

    $("#btn_rnr").click(function(){
        $('#rule_and_regulation').toggle();
    });
});
</script>

app/views/attachments/show.html.erb
<%- model_class = Attachment -%>
<div class="">
  <h4><%=t '.title', :default => model_class.model_name.human %></h4>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:membership_application_id) %>:</strong></dt>
  <dd><%= @attachment.membership_application.name if @attachment.membership_application.present? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attachment_type) %>:</strong></dt>
  <dd><%= @attachment.attachment_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:file_attachment) %>:</strong></dt>
  <dd><%= image_tag @attachment.file_attachment.url(:medium) %></dd>
</dl>

<div class="form-actions">
<% if user_signed_in? %>
  <%= link_to t('.back', :default => t("helpers.links.back")), attachments_path, :class => 'btn'  %>
  <!-- <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_attachment_path(@attachment), :class => 'btn btn-primary' unless current_user.role == 'Member'  %> -->
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")), attachment_path(@attachment), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' if current_user.role == 'Admin' %>
<% else %>
  <!-- <%= link_to 'New', "/attachments/new?membership_application_ref_no=#{@ref_no}", :class => 'btn btn-primary' %> -->
  <%= link_to 'Done', "/successful?membership_application_ref_no=#{@ref_no}", :class => 'btn btn-primary' %>
  <br/>
  <br/>
<% end %>
</div>
<br/>