config/routes.rb
Rails.application.routes.draw do
	
  resources :degrees
  resources :photos
  # dashboard links for member

  # CSV Exports for ecmembers, committee members, members
  get "/export-ecmembers" => 'ecmembers#csv_export', as: 'csv_export_ecmembers'
  get "/export-committee_members" => 'committee_members#csv_export', as: 'csv_export_committee_members'
  get "/export-members" => 'members#csv_export', as: 'csv_export_members'


  get "/d/announcements" => "dashboard#announcements"
  get "/d/announcement/:id" => "dashboard#announcement", as: 'd_announcement'
  get "/d/attachments" => "dashboard#attachments"
  get "/d/attachment/:id" => "dashboard#attachment", as: 'd_attachment'
  get "/d/members" => "dashboard#members"
  get "/d/member_information" => "dashboard#member"
  get "/d/organizations" => "dashboard#organizations"
  get "/d/ecmembers" => "dashboard#ecmembers"
  get "/d/committees" => "dashboard#committees"
  get "/d/committee_members" => "dashboard#committee_members"



  # Edit password only
  get '/users/edit_information' => "users#edit_information", as: 'user_edit_information'
  post '/users/update_information' => "users#update_information", as: 'user_update_information'


  post '/users' => 'users#create'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }, path_names: {sign_up: 'creating_an_account_is_not_an_option' }
  
  resources :api_keys
  resources :announcements

  resources :committee_members
  resources :ecmembers
  resources :members
  resources :users
  
  resources :membership_applications
  resources :memberships
  resources :attachments
  resources :requests
  
  resources :committees
  resources :organizations

  # resources :access_controls
  # resources :permissions
  # resources :events
  # resources :member_data
  # resources :comittees
  
  get '/apply' => 'membership_applications#new', as: 'new_application'
	
  resources :states
  resources :townships
  resources :staffs

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # township populated when state is chosen
  get '/state_search' => 'membership_applications#state_search', as: 'state_search'

  # Email and role populated according to staff or member id in user form
  get '/populate_by_staff_id' => 'users#populate_by_staff_id', as: 'populate_by_staff_id'
  get '/populate_by_member_id' => 'users#populate_by_member_id', as: 'populate_by_member_id'

  root to: 'dashboard#index' 
  get 'index.xlsx' => 'members#export_excel'



  # Extend/Upgrade membership
  get '/memberships/:id/upgrade' => 'memberships#upgrade', as: 'upgrade_membership'
  post '/memberships/:id/upgrade' => 'memberships#upgraded'
  get '/memberships/:id/extend' => 'memberships#extend', as: 'extend_membership'
  post '/memberships/:id/extend' => 'memberships#extended'

  get 'requests/:id/accept' => 'requests#accept', as: 'accept_request'
  get 'requests/:id/reject' => 'requests#reject', as: ''

  get '/reports' => "report#index", as: 'report'

  get '/successful' => "membership_applications#successful"
  get '/accept/:id' => "membership_applications#accept", as: 'accept_membership_application_request'
  get '/reject/:id' => "membership_applications#reject", as: 'reject_membership_application_request'
  get '/done' => "membership_applications#done"
 
# CSV import for existing member list for each organization
  get '/csv_import' => 'members#csv_import', as: "csv_import"
  post '/member_list_csv_import' => 'members#member_list_csv_import', as: "member_list_csv_import"


# API key and Api 
  get '/display' => 'api_version1#display'
  get '/access_control/:id' => 'api_version1#access_control'
  get '/announcement/:id' => 'api_version1#announcement'
  get '/attachment/:id' => 'api_version1#attachment'


  get '/ecmember/:id' => 'api_version1#ecmember'
  get '/event/:id' => 'api_version1#event'
  get '/member_datum/:id' => 'api_version1#member_datum'
  get '/member/:id' => 'api_version1#member'
  get '/membership_application/:id' => 'api_version1#membership_application'
  get '/membership/:id' => 'api_version1#membership'
  get '/organization/:id' => 'api_version1#organization'

  get '/staff/:id' => 'api_version1#staff'
  get '/state/:id' => 'api_version1#state'
  get '/township/:id' => 'api_version1#township'
  get '/user/:id' => 'api_version1#user'


  get '/member_info_edit' => "members#member_info_edit"
  post '/member_info_edit' => "members#member_info_update"


  get '/member_search' => "ecmembers#member_search"


  get "/organization_lvl_report" => "report#organization_lvl_report"
end

app/models/degree.rb
class Degree < ApplicationRecord
	belongs_to :membership_application
	
	has_attached_file :degree_file, styles: { large: "600x800>", medium: "300x300>", small: "150x150>" }, default_url: "/images/:style/missing.png"

	validates_presence_of :degree_title
	validates_attachment :degree_file, presence: true,
	  content_type: { content_type: %w(image/jpeg image/jpg image/png application/pdf) },
	  size: { in: 0..2.megabytes }
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  layout :custom_layout#"apply", only: [:new, :create]
  before_action :is_login?, except: [:show, :new, :create]
  before_action :is_admin?, only: [:destroy]
  before_action :set_degree, only: [:show, :edit, :update, :destroy]

  # GET /degrees
  # GET /degrees.json
  def index
    @degrees = Degree.all
  end

  # GET /degrees/1
  # GET /degrees/1.json
  def show
  end

  # GET /degrees/new
  def new
    unless params[:membership_application_ref_no].present?
      redirect_to root_path
    end
    @degree = Degree.new
    @degree.membership_application_id = MembershipApplication.find_by_ref_no(params[:membership_application_ref_no]).id if params[:membership_application_ref_no].present? && MembershipApplication.find_by_ref_no(params[:membership_application_ref_no]).present?
  end

  # GET /degrees/1/edit
  def edit
  end

  # POST /degrees
  # POST /degrees.json
  def create
    @degree = Degree.new(degree_params)
    @degree.membership_application_id = MembershipApplication.find_by_name(params[:degree][:membership_application_id]).id

    respond_to do |format|
      if @degree.save
        format.html { redirect_to "/attachments/new?membership_application_ref_no=#{@degree.membership_application.ref_no}", notice: 'Photo was successfully created.' }
        format.html { redirect_to @degree, notice: 'Degree was successfully created.' }
        format.json { render :show, status: :created, location: @degree }
      else
        format.html { render :new }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degrees/1
  # PATCH/PUT /degrees/1.json
  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to @degree, notice: 'Degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1
  # DELETE /degrees/1.json
  def destroy
    @degree.destroy
    respond_to do |format|
      format.html { redirect_to degrees_url, notice: 'Degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected
  def custom_layout
    if !user_signed_in? || (user_signed_in? && current_user.role == 'Member' && action_name == 'new')
      "apply"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_params
      params.require(:degree).permit(:degree_title, :membership_application_id, :degree_file)
    end

    # Check login
    def is_login?
      unless user_signed_in?
        redirect_to new_user_session_path
      else
        if current_user.role == 'Member'
          redirect_to '/d/attachments'
        end
      end
    end

    # Only staff can access this model
    def is_staff?
      unless user_signed_in? && current_user.role != "Member"
        redirect_to root_path, notice: 'Access Denied'
      end
    end
    def is_admin?
      unless user_signed_in? && current_user.role == "Admin"
        redirect_to root_path, notice: 'Access Denied'
      end
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/views/degrees/_form.html.erb
<%= form_for @degree, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @degree.errors.any? %>
    <strong><%= @degree.errors.count %> errors detected.</strong>
    <ul>
    <% @degree.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group col-md-12">
    <%= f.label :membership_application_id, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
      <input type="text" id="degree_membership_application" name="degree[membership_application_id]" value="<%= @degree.membership_application.name if @degree.membership_application.present? %>" class="form-control" readonly>
    </div>
  </div>

  <div class="form-group col-md-12">
    <%= f.label :degree_title, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
      <%= f.text_field :degree_title, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group col-md-12">
    <%= f.label :degree_file, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
      <%= f.file_field :degree_file, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <!-- <%= link_to t('.cancel', :default => t("helpers.links.cancel")), degrees_path, :class => 'btn' %> -->
    <br/><br/>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<%- model_class = Degree -%>
<div class="page-header">
  <h4><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h4>
</div>
<%= render :partial => 'form' %>

app/views/degrees/index.html.erb
<%- model_class = Degree -%>
<div class="page-header">
  <h4><%=t '.title', :default => model_class.model_name.human.pluralize %></h4>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:degree_title) %></th>
      <th><%= model_class.human_attribute_name(:membership_application_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @degrees.each do |degree| %>
      <tr>
        <td><%= link_to degree.id, degree_path(degree) %></td>
        <td><%= degree.degree_title %></td>
        <td><%= degree.membership_application_id %></td>
        <td><%=l degree.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_degree_path(degree), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      degree_path(degree),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_degree_path,
            :class => 'btn btn-primary' %>

app/views/degrees/new.html.erb
<%- model_class = Degree -%>
<div class="">
	<%= image_tag 'mcpa_logo', style: "width:80px;", class:"pull-right" %> 
	<h4><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "Degree for Membership application #{@degree.membership_application.name if @degree.membership_application.present? }") %></h4>
</div>
<div class="col-xs-12">
	<strong>Upload the profile picture for the membership.</strong>
</div>
<%= render :partial => 'form' %>

app/views/degrees/show.html.erb
<%- model_class = Degree -%>
<div class="page-header">
  <h4><%=t '.title', :default => model_class.model_name.human %></h4>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:degree_title) %>:</strong></dt>
  <dd><%= @degree.degree_title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:membership_application_id) %>:</strong></dt>
  <dd><%= @degree.membership_application_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              degrees_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_degree_path(@degree), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              degree_path(@degree),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>